# docker-compose.dev.yml
services:
  php:
    build:
      context: .
      target: dev
      args:
        ROOT_PASS: ${ROOT_PASS:-guacamole}
    working_dir: /var/munkireport
    volumes:
      - mr_db:/var/munkireport/storage/db
    ports:
      - "8080:80"
    environment:
      - CONNECTION_DRIVER="sqlite"
      - CONNECTION_DATABASE=/var/munkireport/storage/db/mr.db
      - MR_PASSPHRASE=
      - AUTH_METHODS="NOAUTH"
      - APP_ENV=local
      - DEBUG=FALSE
      - XDEBUG_MODE=develop,coverage

volumes:
  mr_db: