# docker-compose.dev.yml
version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: munkireport
      MYSQL_USER: reportingadmin
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    volumes:
      # persistent data
      - mysql_data:/var/lib/mysql
      # --- TLS material ---------------------------
      - ./tls/ca.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./tls/mysql.crt:/etc/mysql/ssl-cert.pem:ro
      - ./tls/mysql.key:/etc/mysql/ssl-key.pem:ro
    command: >
      --require_secure_transport=ON
      --ssl_ca=/etc/ssl/certs/ca-certificates.crt
      --ssl_cert=/etc/mysql/ssl-cert.pem
      --ssl_key=/etc/mysql/ssl-key.pem
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -pchangeme -ureportingadmin -h localhost"]
      interval: 5s
      timeout: 2s
      retries: 10

  php:
    build:
      context: .
      target: prod
      args:
        ROOT_PASS: ${ROOT_PASS:-guacamole}
    container_name: mr-web
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /var/munkireport
    volumes:
      - ./tls/ca.crt:/etc/ssl/certs/ca-certificates.crt:ro
    ports:
      - "8080:80"       # browse http://localhost:8080
      - "2222:2222"     # optional: SSH into the container
    environment:
      # ---- MunkiReport ↓ ----------------------------------------------------
      CONNECTION_DRIVER: "mysql"
      CONNECTION_HOST:   "mysql"
      CONNECTION_PORT:   "3306"
      CONNECTION_DATABASE: "munkireport"
      CONNECTION_USERNAME: "reportingadmin"
      CONNECTION_PASSWORD: "changeme"

      # TLS for every MySQL client (PDO & mysqli)
      CONNECTION_SSL_ENABLED:    "TRUE"
      CONNECTION_SSL_CA:     "/etc/ssl/certs/ca-certificates.crt"
      MYSQL_ATTR_SSL_CA:     "/etc/ssl/certs/ca-certificates.crt"
      MYSQLI_CLIENT_SSL_CA:  "/etc/ssl/certs/ca-certificates.crt"
      PDO_MYSQL_ATTR_SSL_CA: "/etc/ssl/certs/ca-certificates.crt"
      PDO_MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: "1"
      MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT: "1"

      # ---- general app ------------------------------------------------------
      APP_ENV: "production"
      APP_DEBUG: "false"
      DEBUG: "FALSE"
      AUTH_METHODS: "NOAUTH"
      XDEBUG_MODE: "develop,coverage"

volumes:
  mysql_data: {}
  mr_db: {}
