name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: containersdevopsecu.azurecr.io
  IMAGE_NAME: managedreport-custom

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # ──────────────────────────────────────────────────────────────
      # Checkout source
      # ──────────────────────────────────────────────────────────────
      - uses: actions/checkout@v4

      # Buildx & registry login
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # ──────────────────────────────────────────────────────────────
      # Generate image metadata (tags, labels)
      # ──────────────────────────────────────────────────────────────
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short        # <commit-SHA>
            type=ref,event=branch        # <branch-name>
            type=raw,value=latest        # latest

      # ──────────────────────────────────────────────────────────────
      # Build production image
      # ──────────────────────────────────────────────────────────────
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ROOT_PASS=${{ secrets.SSH_PASSWORD }}