# .github/workflows/azure-registry.yml
name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: containersdevopsecu.azurecr.io
  IMAGE_NAME: managedreport-custom

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}

    steps:
    # ──────────────────────────────────────────────────────────────
    # 1. checkout + login
    # ──────────────────────────────────────────────────────────────
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # ──────────────────────────────────────────────────────────────
    # 2. generate metadata           <-- only `sha-short` + `branch`
    # ──────────────────────────────────────────────────────────────
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,format=short        # e.g. 8b5e4f1
          type=ref,event=branch        # e.g. main

    # ── grab the first tag (the sha-short) and expose it ─────────────
    - id: set-tag
      shell: bash
      run: |
        # first tag returned by metadata-action is the sha-short one
        SHA_TAG="$(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1)"

        echo "SHA_TAG resolved to: ${SHA_TAG}"

        ## make it an *environment variable* for the rest of this job
        echo "IMAGE_TAG=${SHA_TAG}" >> "${GITHUB_ENV}"

        ## expose it as an *output* for downstream jobs
        echo "image_tag=${SHA_TAG}" >> "${GITHUB_OUTPUT}"

    # ──────────────────────────────────────────────────────────────
    # 3. build & push
    # ──────────────────────────────────────────────────────────────
    - uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        target: prod
        push: true
        tags: ${{ steps.meta.outputs.tags }}   # pushes sha + branch
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ROOT_PASS=${{ secrets.SSH_PASSWORD }}